import os
import time

def clear():
    os.system('cls' if os.name == 'nt' else 'clear')

def purple_eats_a_cheesebuger():
    clear()
    print("Eating a cheeseburger...")
    print("🟪              🍔")
    time.sleep(0.5)
    clear()
    print("Eating a cheeseburger...")
    print("🟪             🍔")
    time.sleep(0.5)
    clear()
    print("Eating a cheeseburger...")
    print("🟪           🍔")
    time.sleep(0.5)
    clear()
    print("Eating a cheeseburger...")
    print("🟪          🍔")
    time.sleep(0.5)
    clear()
    print("Eating a cheeseburger...")
    print("🟪         🍔")
    time.sleep(0.5)
    clear()
    print("Eating a cheeseburger...")
    print("🟪         🍔")
    time.sleep(0.5)
    clear()
    print("Eating a cheeseburger...")
    print("🟪        🍔")
    time.sleep(0.5)
    clear()
    print("Eating a cheeseburger...")
    print("🟪       🍔")
    time.sleep(0.5)
    clear()
    print("Eating a cheeseburger...")
    print("🟪      🍔")
    time.sleep(0.5)
    clear()
    print("Eating a cheeseburger...")
    print("🟪     🍔")
    time.sleep(0.5)
    clear()
    print("Eating a cheeseburger...")
    print("🟪    🍔")
    time.sleep(0.5)
    clear()
    print("Eating a cheeseburger...")
    print("🟪   🍔")
    time.sleep(0.5)
    clear()
    print("Eating a cheeseburger...")
    print("🟪  🍔")
    time.sleep(0.5)
    clear()
    print("Eating a cheeseburger...")
    print("🟪 🍔")
    time.sleep(0.5)
    clear()
    print("Eating a cheeseburger...")
    print("🟪🍔")
    time.sleep(0.5)
    clear()
    print("Cheeseburger eaten!")
    print("🟪")
    input("\nPRESS ENTER TO RESTART")
    start()

def cheese_burger_eats_a_purple():
    clear()
    print("Eating a purple...")
    print("🍔              🟪")
    time.sleep(0.5)
    clear()
    print("Eating a purple...")
    print("🍔             🟪")
    time.sleep(0.5)
    clear()
    print("Eating a purple...")
    print("🍔           🟪")
    time.sleep(0.5)
    clear()
    print("Eating a purple...")
    print("🍔          🟪")
    time.sleep(0.5)
    clear()
    print("Eating a purple...")
    print("🍔         🟪")
    time.sleep(0.5)
    clear()
    print("Eating a purple...")
    print("🍔         🟪")
    time.sleep(0.5)
    clear()
    print("Eating a purple...")
    print("🍔        🟪")
    time.sleep(0.5)
    clear()
    print("Eating a purple...")
    print("🍔       🟪")
    time.sleep(0.5)
    clear()
    print("Eating a purple...")
    print("🍔      🟪")
    time.sleep(0.5)
    clear()
    print("Eating a purple...")
    print("🍔     🟪")
    time.sleep(0.5)
    clear()
    print("Eating a purple...")
    print("🍔    🟪")
    time.sleep(0.5)
    clear()
    print("Eating a purple...")
    print("🍔   🟪")
    time.sleep(0.5)
    clear()
    print("Eating a purple...")
    print("🍔  🟪")
    time.sleep(0.5)
    clear()
    print("Eating a purple...")
    print("🍔 🟪")
    time.sleep(0.5)
    clear()
    print("Eating a purple...")
    print("🍔🟪")
    time.sleep(0.5)
    clear()
    print("Purple eaten!")
    print("🍔")
    input("\nPRESS ENTER TO RESTART")
    start()
def purple_eats_a_eating_a_cheeseburger_eating_purple():
    clear()
    print("Eating a purple eating cheeseburger eating purple...")
    print("🍔              🟪")
    time.sleep(0.5)
    clear()
    print("Eating a purple eating cheeseburger eating purple...")
    print(" 🍔            🟪")
    time.sleep(0.5)
    clear()
    print("Eating a purple eating cheeseburger eating purple...")
    print("  🍔          🟪")
    time.sleep(0.5)
    clear()
    print("Eating a purple eating cheeseburger eating purple...")
    print("   🍔          🟪")
    time.sleep(0.5)
    clear()
    print("Eating a purple eating cheeseburger eating purple...")
    print("   🍔         🟪")
    time.sleep(0.5)
    clear()
    print("Eating a purple eating cheeseburger eating purple...")
    print("    🍔         🟪")
    time.sleep(0.5)
    clear()
    print("Eating a purple eating cheeseburger eating purple...")
    print("     🍔        🟪")
    time.sleep(0.5)
    clear()
    print("Eating a purple eating cheeseburger eating purple...")
    print("      🍔       🟪")
    time.sleep(0.5)
    clear()
    print("Eating a purple eating cheeseburger eating purple...")
    print("       🍔      🟪")
    time.sleep(0.5)
    clear()
    print("Eating a purple eating cheeseburger eating purple...")
    print("        🍔     🟪")
    time.sleep(0.5)
    clear()
    print("Eating a purple eating cheeseburger eating purple...")
    print("         🍔    🟪")
    time.sleep(0.5)
    clear()
    print("Eating a purple eating cheeseburger eating purple...")
    print("          🍔   🟪")
    time.sleep(0.5)
    clear()
    print("Eating a purple eating cheeseburger eating purple...")
    print("           🍔  🟪")
    time.sleep(0.5)
    clear()
    print("Eating a purple eating cheeseburger eating purple...")
    print("            🍔 🟪")
    time.sleep(0.5)
    clear()
    print("Eating a purple eating cheeseburger eating purple...")
    print("             🍔🟪")
    time.sleep(0.5)
    clear()
    print("Purple eating cheeseburger eating purple eaten!")
    print("              💣")
    time.sleep(0.5)
    clear()
    print("Purple eating cheeseburger eating purple eaten!")
    print("              💥")
    input("\nPRESS ENTER TO RESTART")
    start()
def purple_does_not_eat_a_cheeseburger():
    clear()
    print("Purple did not eat the cheeseburger ):")
    input("\nPRESS ENTER TO RESTART")
    start()

def start():
    clear()
    print("Welcome to.. If D = 10 PURPLE EATS A CHEESE BURGER")
    D = input("\nD = ")
    if D == "10":
        purple_eats_a_cheesebuger()
    elif D == "9":
        cheese_burger_eats_a_purple()
    elif D == "910":
        purple_eats_a_eating_a_cheeseburger_eating_purple()
        
    else:
        purple_does_not_eat_a_cheeseburger()
    

start()
