import os
import time

def clear():
    os.system('cls' if os.name == 'nt' else 'clear')

def purple_eats_a_cheesebuger():
    clear()
    print("Eating a cheeseburger...")
    print("🟪              🍔")
    time.sleep(0.5)
    clear()
    print("Eating a cheeseburger...")
    print("🟪             🍔")
    time.sleep(0.5)
    clear()
    print("Eating a cheeseburger...")
    print("🟪           🍔")
    time.sleep(0.5)
    clear()
    print("Eating a cheeseburger...")
    print("🟪          🍔")
    time.sleep(0.5)
    clear()
    print("Eating a cheeseburger...")
    print("🟪         🍔")
    time.sleep(0.5)
    clear()
    print("Eating a cheeseburger...")
    print("🟪         🍔")
    time.sleep(0.5)
    clear()
    print("Eating a cheeseburger...")
    print("🟪        🍔")
    time.sleep(0.5)
    clear()
    print("Eating a cheeseburger...")
    print("🟪       🍔")
    time.sleep(0.5)
    clear()
    print("Eating a cheeseburger...")
    print("🟪      🍔")
    time.sleep(0.5)
    clear()
    print("Eating a cheeseburger...")
    print("🟪     🍔")
    time.sleep(0.5)
    clear()
    print("Eating a cheeseburger...")
    print("🟪    🍔")
    time.sleep(0.5)
    clear()
    print("Eating a cheeseburger...")
    print("🟪   🍔")
    time.sleep(0.5)
    clear()
    print("Eating a cheeseburger...")
    print("🟪  🍔")
    time.sleep(0.5)
    clear()
    print("Eating a cheeseburger...")
    print("🟪 🍔")
    time.sleep(0.5)
    clear()
    print("Eating a cheeseburger...")
    print("🟪🍔")
    time.sleep(0.5)
    clear()
    print("Cheeseburger eaten!")
    print("🟪")
def purple_does_not_eat_a_cheeseburger():
    print("Purple did not eat the cheeseburger ):")
clear()
print("Welcome to.. If D = 10 PURPLE EATS A CHEESE BURGER")
D = input("\nD = ")
if D == "10":
    purple_eats_a_cheesebuger()
else:
    purple_does_not_eat_a_cheeseburger()
